# Generated by Django 4.0.5 on 2022-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_links'),
        ('accounts', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_links',
            field=models.ManyToManyField(blank=True, to='catalog.links'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_videos',
            field=models.ManyToManyField(blank=True, to='catalog.videos'),
        ),
    ]
