# Generated by Django 3.1.6 on 2021-02-28 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a map (e.g. Inferno)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=100)),
                ('type_video', models.CharField(blank=True, choices=[('Smoke', 'smoke'), ('Molly', 'molly'), ('Flash', 'flash')], max_length=6)),
                ('site', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('mid', 'Middle')], default='a', max_length=3)),
                ('map_belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.maps')),
            ],
        ),
    ]
