# Generated by Django 3.1.6 on 2021-02-16 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a map (e.g. Inferno)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.TextField(help_text='Enter the link', max_length=1000)),
                ('map', models.ManyToManyField(help_text='Select a map for this video', to='catalog.Map')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video across whole library', primary_key=True, serialize=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.video')),
            ],
        ),
    ]
