# Generated by Django 3.1.6 on 2021-02-18 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video across whole library', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='VideoInstance',
        ),
    ]
