# Generated by Django 3.1.6 on 2021-03-20 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maps',
            options={'verbose_name': 'Map'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video'},
        ),
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
