# Generated by Django 4.0.5 on 2022-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210320_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='admin_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videos',
            name='type_video',
            field=models.CharField(blank=True, choices=[('Smoke', 'smoke'), ('Molly', 'molly'), ('Flash', 'flash'), ('Nade', 'grenade'), ('Strat', 'strat'), ('Misc', 'misc')], max_length=6),
        ),
    ]
