# Generated by Django 3.1.6 on 2021-02-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210217_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type_video',
            field=models.CharField(blank=True, choices=[('Smoke', 'smoke'), ('Molly', 'molly'), ('Flash', 'flash')], help_text='Pick a type', max_length=6),
        ),
    ]
