# Generated by Django 3.1.6 on 2021-02-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_video_type_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Map',
            new_name='Maps',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Videos',
        ),
    ]
