# Generated by Django 3.1.6 on 2021-02-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210219_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='map',
            new_name='map_belong',
        ),
    ]
