# Generated by Django 3.1.6 on 2021-02-20 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210219_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='map_belong',
        ),
        migrations.AddField(
            model_name='videos',
            name='map_belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.maps'),
        ),
    ]
