# Generated by Django 3.1.6 on 2021-02-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210219_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a map (e.g. Inferno)', max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('map_belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.maps')),
            ],
        ),
    ]
