# Generated by Django 3.1.6 on 2021-02-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_callouts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Callouts',
        ),
    ]
