# Generated by Django 3.1.6 on 2021-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_callouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.TextField(help_text='Enter the link', max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='site',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('mid', 'Middle')], default='a', max_length=3),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='videos',
            name='type_video',
            field=models.CharField(blank=True, choices=[('Smoke', 'smoke'), ('Molly', 'molly'), ('Flash', 'flash')], max_length=6),
        ),
    ]
