# Generated by Django 3.1.6 on 2021-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210226_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(help_text='Enter the link', max_length=100),
        ),
    ]
